name: Job Assistant

on:
  schedule:
    - cron: '0 5,17 * * *'  # 08:00 & 20:00 Israel time (UTC+3)
  workflow_dispatch:       # allow manual trigger

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: python job_assistant.py
        env:
          OPENAI_API_KEY:            ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_TOKEN:            ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID:          ${{ secrets.TELEGRAM_CHAT_ID }}
          SERVICE_ACCOUNT_JSON_B64:  ${{ secrets.SERVICE_ACCOUNT_JSON_B64 }}
          GOOGLE_SHEETS_ID:          ${{ secrets.GOOGLE_SHEETS_ID }}
          GOOGLE_SHEET_CONFIG_TAB:   ${{ secrets.GOOGLE_SHEET_CONFIG_TAB }}
          GOOGLE_SHEET_APP_TAB:      ${{ secrets.GOOGLE_SHEET_APP_TAB }}
          DRIVE_FOLDER_ID:           ${{ secrets.DRIVE_FOLDER_ID }}
